#logging:
#  level:
#    com.asgames.ataliasflame.domain.services:
#      CharacterInitializer: debug
#      CombatService: debug

spring:
  datasource:
    url: jdbc:h2:file:/h2db/ataliasflame
    username: user
    password: pw
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelogs.yaml
