package com.asgames.ataliasflame.domain.model.enums;

public enum ItemCode {
    FIST, STAFF, DAGGER, SPEAR, SWORD,
    BUCKLER, ROUND_SHIELD, KITE_SHIELD, TOWER_SHIELD,
    LINEN_ARMOR, LEATHER_ARMOR, STUDDED_LEATHER_ARMOR, CHAIN_MAIL, PLATE_MAIL, FULL_PLATE_MAIL,
    WATER, BREAD, FRUIT, MEAT, HEALING_HERB
}
