package com.asgames.ataliasflame.domain.model.enums;

public enum SpellName {
    FIREBALL,
    LIGHTNING_STRIKE,
    INFERNO,
    GLACIAL_BLOW,
    BLADES_OF_JUDGEMENT,
    BALL_OF_ENERGY,
    SOUL_OUTBURST,
    WRATH_OF_NATURE,
    SPLITTING_WIND,
    DIVINE_HAMMER,
    CALLING_THE_SOULS,
    CALLING_ANIMALS,
    SUMMON_GUARDIAN,
    PROJECTION_OF_ENERGY,
    FRIEND_IN_NEED
}
